export const info = [{
    "name": "Daa Major",
    "job": "Rapper",
    "class": "1",
    "position": "1",
    "jobItem": "Sing Writer",
    "img": "./assets/images/S1.jpg",
    "quantity": "Over 50 milions",
    "social": "Views on Youtube",
}, {
    "name": "Lil' Flow",
    "job": "Rapper",
    "class": "2",
    "position": "2",
    "jobItem": "Sing Writer",
    "img": "./assets/images/S2.jpg",
    "quantity": "Over 30 million",
    "social": "Followers on Instagram",
}, {
    "name": "MC Beats",
    "job": "Producer",
    "class": "3",
    "position": "3",
    "jobItem": "Sing Writer",
    "img": "./assets/images/S3.jpg",
    "quantity": "Over 50 milions",
    "social": "Views on Youtube",
}, {
    "name": "DJ Rhyme",
    "job": "Rapper",
    "class": "4",
    "position": "4",
    "jobItem": "Sing Writer",
    "img": "./assets/images/S4.jpg",
    "quantity": "Over 50 milions",
    "social": "Views on Youtube",
}, {
    "name": "Queen Lyric",
    "job": "Rapper",
    "class": "5",
    "position": "5",
    "jobItem": "Sing Writer",
    "img": "./assets/images/S5.jpg",
    "quantity": "Over 50 milions",
    "social": "Plays on SoundCloud",
}];

